### PR TITLE
Updated find_element method

### PR DESCRIPTION
**Pull request by dysphere**
The old methods of finding elements is deprecated in Selenium so I updated it to be more current.

### CODE REVIEW

**Comment by baijum** [comment]
@anarang Can you please review this PR?

**Comment by anarang** [comment]
@baijum sure, I can take a look.
@dysphere can you specify the selenium version and are you sure that old method of finding elements is deprecated in Selenium? imo, both work.

**Comment by ajoga** [comment]
Hi @anarang 

> @dysphere can you specify the selenium version and are you sure that old method of finding elements is deprecated in Selenium? imo, both work.

The depreciation warning were introduced in selenium 4.0 alpha 5 : https://github.com/SeleniumHQ/selenium/blob/ac4d0fdd4a326e638ff82df00fe4a512527cb532/py/CHANGES#L282

**Comment by anarang** [comment]
@ajoga the changes look to me.
cc: @baijum

**Comment by baijum** [comment]
Thanks @dysphere for the PR! And tanks to @ajoga and @anarang for taking this forward.

**Comment by ajoga** [comment]
Thank you for the tight feedback loop @anarang & @baijum !

**Pull request merged**
